# For Node.js/Next.js development
FROM mcr.microsoft.com/devcontainers/typescript-node:20

# [Optional] Install additional OS packages you want here
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install global node packages
# RUN npm install -g <your-package-name>

# [Optional] Set the default shell to bash instead of sh
# SHELL ["/bin/bash", "-c"]
